/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueryImport } from './routes/query'
import { Route as AbortImport } from './routes/abort'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const QueryRoute = QueryImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any)

const AbortRoute = AbortImport.update({
  id: '/abort',
  path: '/abort',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/abort': {
      id: '/abort'
      path: '/abort'
      fullPath: '/abort'
      preLoaderRoute: typeof AbortImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abort': typeof AbortRoute
  '/query': typeof QueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abort': typeof AbortRoute
  '/query': typeof QueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/abort': typeof AbortRoute
  '/query': typeof QueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abort' | '/query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abort' | '/query'
  id: '__root__' | '/' | '/abort' | '/query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbortRoute: typeof AbortRoute
  QueryRoute: typeof QueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbortRoute: AbortRoute,
  QueryRoute: QueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/abort",
        "/query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/abort": {
      "filePath": "abort.tsx"
    },
    "/query": {
      "filePath": "query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
